### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by prksastry** [SkyLined/BugId#101]
Though I am writing it as an issue, but is there no alternate process of procuring commercial/non commercial licenses other than your official website and checkout via card? I am finding out for global resellers of skylined products, across different countries, if you have any resellers in South Asia/Indian subcontinent, please give the details

**Comment by SkyLined** [comment]
Hi,

Please email skylined@skylined.nl for any questions and information about licensing and payment.

Cheers,

BJ
