### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by TecR0c** [SkyLined/BugId#103]
bug report attached
[bug-id-errors (1).txt](https://github.com/SkyLined/BugId/files/8055760/bug-id-errors.1.txt)

**Comment by SkyLined** [comment]
I believe I already fixed this in the main branch here:
https://github.com/SkyLined/BugId/commit/1b77a71cd35e76836592cc1ed9622aeb7faea8dc#diff-04a0b0ef6207c54883c222f934942f17739e6b18a88df4ea34e99a44cc511a83L422

I'm planning to push a new release version with this and other improvements soon.
