### ISSUE TITLE
stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by z1r00** [SkyLined/BugId#120]
<img width="1399" alt="image" src="https://github.com/SkyLined/BugId/assets/68418072/289e43b6-8db1-400a-ae0c-ee00415fe12f">
why?

**Comment by z1r00** [comment]
<img width="1470" alt="image" src="https://github.com/SkyLined/BugId/assets/68418072/be534afe-39d2-4d4f-aaf3-acb312aae89e">

**Comment by SkyLined** [comment]
Looks like:
1. you do not have Debugging Tools for Windows installed
2. The code is not handling this by reporting this problem to you as it should but rather it causes an exception.

Can you make sure you have Debugging Tools for Windows installed? If you do, can you let me know where `cdb.exe` is located?

**Comment by z1r00** [comment]
I didn't find cdb.exe, but I downloaded windbg

**Comment by SkyLined** [comment]
The unhandled exception this caused was fixed
https://github.com/SkyLined/mBugId/commit/3c84f8f788d1735c43ac844ebf21cb7b1d23178f
