### ISSUE TITLE
ImportError: No module named FileSystem

### ISSUE THREAD

**Issue by kokanin** [SkyLined/BugId#17]
C:\BugId-master\modules\cBugId>Tests.cmd
Traceback (most recent call last):
  File "Tests\Tests.py", line 11, in <module>
    from cBugId import cBugId;
  File "C:\BugId-master\modules\cBugId\cBugId.py", line 2, in <module>
    from cCdbWrapper import cCdbWrapper;
  File "C:\BugId-master\modules\cBugId\cCdbWrapper.py", line 4, in <module>
    from cCdbWrapper_fasReadOutput import cCdbWrapper_fasReadOutput;
  File "C:\BugId-master\modules\cBugId\cCdbWrapper_fasReadOutput.py", line 3, in
 <module>
    from FileSystem import FileSystem;
ImportError: No module named FileSystem

**Comment by kokanin** [comment]
same for the kill module

**Comment by kokanin** [comment]
disregard this, i downloaded the zip instead of using git which didn't resolve stuff

**Comment by SkyLined** [comment]
Thanks! You did actually run into a bug: the code should check if FileSystem and Kill are present and can be imported. If this fails it should give you an error message that describes the problem and how to resolve it.

However, that check was done too late: after the code already failed to import FileSystem, and threw the exception you saw. I've now moved that check to the right location in the code, so if anyone else runs into this, they should get a more descriptive error message and be able to resolve it more easily.

https://github.com/SkyLined/cBugId/commit/5e4b1eb658afb36adb112b292359121ec92fcbbc

**Comment by kokanin** [comment]
I did a new proper git checkout, and indeed your added changes make it much more obvious what is going on, thanks
