### ISSUE TITLE
adobe reader support

### ISSUE THREAD

**Issue by kokanin** [SkyLined/BugId#19]
Hi, 

Trying to spawn adobe reader under BugId I end up with this:
````
$ python BugId.py "c:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe"
+ The debugger is starting the application...
  Command line: c:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe
+ The application was started successfully and is running...
  * T+0.0 Exception code 0x80000003 (Break instruction exception) was detected and is being analyzed...
  * T+0.0 The application was resumed successfully and is running...
  * T+3.5 Exception code 0xC0000235 (Unknown exception) was detected and is being analyzed...
+ BugId run into an internal error:
  AssertionError('The exception address 0x7786bb47 was not found on the stack\r\n00 0065f35c 7569c585 ntdll!ZwClose+0x12\r\n01 0065f36c 75df1418 KERNELBASE!CloseHandle+0x2d\r\n02 0065f37c 5f73de16 kernel32!CloseHandleImplementation+0x3f\r\nWARNING: Stack unwind information not available. Following frames may be wrong.\r\n03 0065f390 6036f2a1 libcef+0xdde16\r\n04 0065f398 60810032 libcef!cef_time_to_timet+0x1a338\r\n05 0065f400 616a28dc libcef!cef_time_to_timet+0x4bb0c9\r\n06 0065f418 616a2771 libcef!TerminateProcessWithoutDump+0xa808f1\r\n07 0065f434 616a2393 libcef!TerminateProcessWithoutDump+0xa80786\r\n08 0065f5f0 60ebfc28 libcef!TerminateProcessWithoutDump+0xa803a8\r\n09 0065f604 60ebfb86 libcef!TerminateProcessWithoutDump+0x29dc3d\r\n0a 0065f650 60ebf52e libcef!TerminateProcessWithoutDump+0x29db9b\r\n0b 0065f660 60333de9 libcef!TerminateProcessWithoutDump+0x29d543\r\n0c 0065f730 60311e53 libcef!cef_string_list_value+0x7094\r\n0d 0065f754 0029fb59 libcef!cef_execute_process+0x3b\r\n0e 0065f770 0027357c RdrCEF!IsSandboxedProcess+0x2bab0\r\n0f 0065f950 002fdfef RdrCEF!GetHandleVerifier+0x952c\r\n10 0065f99c 75df338a RdrCEF!IsSandboxedProcess+0x89f46\r\n11 0065f9a8 77a39902 kernel32!BaseThreadInitThunk+0xe\r\n12 0065f9e8 77a398d5 ntdll!__RtlUserThreadStart+0x70\r\n13 0065fa00 00000000 ntdll!_RtlUserThreadStart+0x1b',)

  Please report this issue at the below web-page so it can be addressed:
  https://github.com/SkyLined/BugId/issues/new

BugId version 2016.09.08.1416, cBugId version 2016.09.08.1356
This version of BugId is provided free of charge for non-commercial use only.
If you find it useful and would like to make a donation, you can send bitcoin
to 183yyxa9s1s1f7JBpPHPmzQ346y91Rx5DX. Please contact the author if you wish to
use BugId commercially. Contact and licensing information can be found at
https://github.com/SkyLined/BugId#license.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\python27\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\python27\lib\threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "modules\cBugId\cCdbWrapper.py", line 213, in _fThreadWrapper
    oCdbWrapper.fInternalExceptionCallback(oException);
  File "modules\cBugId\cCdbWrapper.py", line 207, in _fThreadWrapper
    fActivity(oCdbWrapper);
  File "modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py", line 274, in cCdbWrapper_fCdbStdInOutThread
    oCdbWrapper.oBugReport = cBugReport.foCreateForException(oCdbWrapper, uExceptionCode, sExceptionDescription);
  File "modules\cBugId\cBugReport.py", line 87, in foCreateForException
    oException = cException.foCreate(oCdbWrapper, uExceptionCode, sExceptionDescription, oStack);
  File "modules\cBugId\cException.py", line 187, in foCreate
    (sCdbLine, "\r\n".join(oStack.asCdbLines)));
AssertionError: The exception address 0x7786bb47 was not found on the stack
00 0065f35c 7569c585 ntdll!ZwClose+0x12
01 0065f36c 75df1418 KERNELBASE!CloseHandle+0x2d
02 0065f37c 5f73de16 kernel32!CloseHandleImplementation+0x3f
WARNING: Stack unwind information not available. Following frames may be wrong.
03 0065f390 6036f2a1 libcef+0xdde16
04 0065f398 60810032 libcef!cef_time_to_timet+0x1a338
05 0065f400 616a28dc libcef!cef_time_to_timet+0x4bb0c9
06 0065f418 616a2771 libcef!TerminateProcessWithoutDump+0xa808f1
07 0065f434 616a2393 libcef!TerminateProcessWithoutDump+0xa80786
08 0065f5f0 60ebfc28 libcef!TerminateProcessWithoutDump+0xa803a8
09 0065f604 60ebfb86 libcef!TerminateProcessWithoutDump+0x29dc3d
0a 0065f650 60ebf52e libcef!TerminateProcessWithoutDump+0x29db9b
0b 0065f660 60333de9 libcef!TerminateProcessWithoutDump+0x29d543
0c 0065f730 60311e53 libcef!cef_string_list_value+0x7094
0d 0065f754 0029fb59 libcef!cef_execute_process+0x3b
0e 0065f770 0027357c RdrCEF!IsSandboxedProcess+0x2bab0
0f 0065f950 002fdfef RdrCEF!GetHandleVerifier+0x952c
10 0065f99c 75df338a RdrCEF!IsSandboxedProcess+0x89f46
11 0065f9a8 77a39902 kernel32!BaseThreadInitThunk+0xe
12 0065f9e8 77a398d5 ntdll!__RtlUserThreadStart+0x70
13 0065fa00 00000000 ntdll!_RtlUserThreadStart+0x1b
````

**Comment by kokanin** [comment]
just a note, same results with the sandbox disabled

**Comment by SkyLined** [comment]
That's odd: I don't get that exception (`0xC0000235`, `STATUS_DLL_NOT_FOUND`) when I run Adobe Reader in BugId: it runs just fine. This means I cannot easily reproduce the issue and fix it.

I'll see if I can find out what the problem could be from the information you provided.

Also, I've took the libarty to add Adobe Reader using the keyword @acrobat, so you can simply run:

    python BugId.py @acrobat repro.pdf

**Comment by SkyLined** [comment]
Btw. if you run BugId with the `--BugId.bOutputStdOut=true` command line switch, it'll show a lot more information that may be useful to finding out what the problem is, as in:

    python BugId.py --BugId.bOutputStdOut=true @acrobat

I'd appreciate a copy+paste of the output, or you can pipe it to a file and add that to the bug, as in:

    python BugId.py --BugId.bOutputStdOut=true @acrobat >output.txt

Then please add output.txt to the bug.

**Comment by SkyLined** [comment]
Sorry, I added support for Adobe Reader, not Reader DC. I'll add the later now...

**Comment by kokanin** [comment]
[output.txt](https://github.com/SkyLined/BugId/files/462447/output.txt)

**Comment by kokanin** [comment]
thanks for adding reader and dc btw, you rock

**Comment by kokanin** [comment]
[output.txt](https://github.com/SkyLined/BugId/files/463361/output.txt)
..and for my next trick, uploading an output.txt which actually shows the bug

**Comment by SkyLined** [comment]
Thanks, sorry for the delay. The problem was no immediately clear from the output, but I've rewritten most of the code involved to be more robust and added better logging. Can you please try again with the latest version? If you still experience the problem, the information BugId outputs should be more useful in tracking down the root cause. 

Here's the related change:
https://github.com/SkyLined/cBugId/commit/250a4e98efb16b93419fb6cec91f7440e45ae168

**Comment by kokanin** [comment]
$ python BugId.py --nExcessiveCPUUsageCheckInitialTimeout=55555 @acrobatdc > newoutput.txt
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\python27\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\python27\lib\threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "modules\cBugId\cCdbWrapper.py", line 213, in _fThreadWrapper
    oCdbWrapper.fInternalExceptionCallback(oException);
  File "modules\cBugId\cCdbWrapper.py", line 207, in _fThreadWrapper
    fActivity(oCdbWrapper);
  File "modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py", line 274, in cCdbWrapper_fCdbStdInOutThread
    oCdbWrapper.oBugReport = cBugReport.foCreateForException(oCdbWrapper, uExceptionCode, sExceptionDescription);
  File "modules\cBugId\cBugReport.py", line 87, in foCreateForException
    oException = cException.foCreate(oCdbWrapper, uExceptionCode, sExceptionDescription, oStack);
  File "modules\cBugId\cException.py", line 188, in foCreate
    bOffByOne and "adjusted " or "",
NameError: global name 'bOffByOne' is not defined

output:
+ Changed config setting nExcessiveCPUUsageCheckInitialTimeout from 5 to 55555.
* Applying application specific settings:
  + Changed config setting nExcessiveCPUUsageCheckInitialTimeout from 55555 to 10.0.
  + Changed config setting BugId.nExcessiveCPUUsagePercent from 90 to 75.
  + Changed config setting nApplicationMaxRunTime from None to 3000.0.
  * The default value for config setting BugId.nExcessiveCPUUsageWormRunTime is 0.5.
  + Changed config setting BugId.nExcessiveCPUUsageCheckInterval from 10.0 to 5.0.
+ The debugger is starting the application...
  Command line: C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe repro.pdf
+ The application was started successfully and is running...
  * T+0.0 Exception code 0x80000003 (Break instruction exception) was detected and is being analyzed...
  * T+0.0 The application was resumed successfully and is running...
  * T+7.3 Exception code 0xC0000235 (Unknown exception) was detected and is being analyzed...
+ BugId run into an internal error:
  NameError("global name 'bOffByOne' is not defined",)

  Please report this issue at the below web-page so it can be addressed:
  https://github.com/SkyLined/BugId/issues/new

BugId version 2016.09.08.2025, cBugId version 2016.09.12.1025
This version of BugId is provided free of charge for non-commercial use only.
If you find it useful and would like to make a donation, you can send bitcoin
to 183yyxa9s1s1f7JBpPHPmzQ346y91Rx5DX. Please contact the author if you wish to
use BugId commercially. Contact and licensing information can be found at
https://github.com/SkyLined/BugId#license.

**Comment by SkyLined** [comment]
Doh!

Can you manually change "bOffByOne" to "bExceptionOffByOne" in cBugId\cException.py, line 188? I'll fix that on github in a minute

**Comment by kokanin** [comment]
[newoutput.txt](https://github.com/SkyLined/BugId/files/467206/newoutput.txt)
attached from latest run

**Comment by SkyLined** [comment]
Sorry, can you run that again with the `--BugId.bOutputStdOut=true` argument?

**Comment by SkyLined** [comment]
This should solve your immediate problem, but not the underlying issue, by ignoring the exception you are encountering (it will be treated similar to other handle closing issues).

https://github.com/SkyLined/cBugId/commit/a7bb45008d652d0d8f4b9dd9a098bf2ddcff0e3e

I'll commit the fix after I've run some tests.

**Comment by kokanin** [comment]
$  python BugId.py --nExcessiveCPUUsageCheckInitialTimeout=55555 @acrobatdc > newoutput.txt
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\python27\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\python27\lib\threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "modules\cBugId\cCdbWrapper.py", line 214, in _fThreadWrapper
    oCdbWrapper.fInternalExceptionCallback(oException);
  File "modules\cBugId\cCdbWrapper.py", line 208, in _fThreadWrapper
    fActivity(oCdbWrapper);
  File "modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py", line 55, in cCdbWrapper_fCdbStdInOutThread
    asIntialCdbOutput = oCdbWrapper.fasReadOutput();
  File "modules\cBugId\cCdbWrapper.py", line 365, in fasReadOutput
    return cCdbWrapper_fasReadOutput(oCdbWrapper, *axArguments, **dxArguments);
  File "modules\cBugId\cCdbWrapper_fasReadOutput.py", line 124, in cCdbWrapper_fasReadOutput
    fasHandleCommonErrorsAndWarningsInOutput(oCdbWrapper, asLines, bHandleSymbolLoadErrors);
  File "modules\cBugId\cCdbWrapper_fasReadOutput.py", line 27, in fasHandleCommonErrorsAndWarningsInOutput
    oCdbWrapper.fStop();
  File "modules\cBugId\cCdbWrapper.py", line 262, in fStop
    oCdbProcess.terminate();
  File "C:\python27\lib\subprocess.py", line 1016, in terminate
    _subprocess.TerminateProcess(self._handle, 1)
WindowsError: [Error 5] Access is denied

**Comment by SkyLined** [comment]
That is an odd issues, which I never would have expected to happen. Either way, the latest version should have a fix for it, can you try again?
https://github.com/SkyLined/cBugId/commit/23daea9371fb88f6f93e456b445fed6768a6487d

**Comment by kokanin** [comment]
[new.txt](https://github.com/SkyLined/BugId/files/470280/new.txt)

**Comment by SkyLined** [comment]
So this is weird in multiple ways:

1. Adobe Reader is throwing a second chance (==fatal) exception. Can you run Reader outside of Bugid using the following command line?

    "c:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe"

It should crash as well, given that the exception is fatal.

2. The exception is reported as happening in code at a completely different address then where code is actually being executed at the moment the exception happens: The ExceptionAddress is 7704bb47, but EIP= 771FFA02. This is why BugId is failing and I have no idea why this would happen.

I can add code to ignore the second problem in this special case, but I'd rather figure out why it is happening. But even if I ignore the second issue, the first issue is still there and this should be a fatal exception. I can add more code to ignore that particular exception completely and see what happens, but I expect Reader will simply be terminated.

I'll have to think on this some more, sorry for the delays and thank you for continuing to help me try to fix this.

**Comment by kokanin** [comment]
no crashes when running it standalone. As i stated earlier bugid also works fine when using --pids to attach post-startup, so it's not that big of a deal, but yeah, weird.

**Comment by SkyLined** [comment]
Sorry for continued delays - I've been quite busy and since I am unable to reproduce it myself, it's hard to analyze... I'm hoping to find some time to work on this soon.

**Comment by kokanin** [comment]
dont stress it at all, as i wrote i can work around the issue by attaching it to the pid instead of using it for launching - while a bit hackish it works for my purposes.

**Comment by soiax** [comment]
Hi, 

I can reproduce this too, crashes the same way for me, only ReaderDC,

But, if you enable pageheap for "C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroCEF\RdrCEF.exe" and run ReaderDc, BugId says:

```
python BugId.py "c:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe"
+ The debugger is starting the application...
  Command line: c:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe
+ The application was started successfully and is running...
  * T+0.0 Exception code 0x80000003 (Break instruction exception) was detected and is being analyzed...
  * T+0.0 The application was resumed successfully and is running...
  * T+2.8 Exception code 0xC0000005 (Access violation) was detected and is being analyzed...
+ A bug was detected in the application.

  === BugId report (https://github.com/SkyLined/BugId) =========================
  Id:               AVW:NULL+0x14 585.bb4
  Location:         RdrCEF.exe!ntdll.dll!RtlpWaitOnCriticalSection
  Description:      Access violation while writing memory at 0x14 using a NULL ptr.
  Version:          RdrCEF.exe 15.17.20050.61080
                    ntdll.dll 10.0.14393.206
  Security impact:  Denial of Service
  Run time:         2.797 seconds
  Bug report:       AVW.NULL+0x14 585.bb4 @ RdrCEF.exe!ntdll.dll!RtlpWaitOnCriticalSection.html (36230 bytes)
```

**Comment by kokanin** [comment]
right, good that it finally "works" for you.

**Comment by SkyLined** [comment]
Hmmm... BugId really only works well with Page Heap enabled - maybe I should warn if you are running a processs in which it is not.

Good to know it is ReaderDC - I only tested Reader. I'll see if I can find some time to install it a=on a VM and test this issue.

**Comment by soiax** [comment]
After the recent Adobe Reader DC update (15.020.20039)  this bug disappeared, BugId (2016.10.05.1407) doesn't crash.

**Comment by SkyLined** [comment]
@kokanin, I'm closing this bug out per the above comment. Please try with the latest version of Reader DC and reopen if you still have this problem. Thanks again for taking the time to help me improve BugId!
