### ISSUE TITLE
Tests fail on Win10x64 / python 2.7?

### ISSUE THREAD

**Issue by bnagy** [SkyLined/BugId#2]
Hi!

I don't usually work with python so it's entirely possible I'm doing something foolish. I did a fairly basic Win10 install, python 27 and then got the zip for BugId master. Is this expected?

```
c:\BugId-master>%cdb% -version
cdb version 10.0.10240.9

c:\BugId-master>c:\Python27\python.exe Tests.py
* Starting tests...
cdb:stderr>R6025
cdb:stderr>- pure virtual function call
- UseAfterFree Read 20 0 =AMD64=> AVR:Free
    => got no error

c:\BugId-master>ver

Microsoft Windows [Version 10.0.10240]
```

**Comment by SkyLined** [comment]
Are you running without page heap? If so, you won't see proper results. I'll update the documentation to mention this explicitly. You can use pageheap.cmd to turn it on.

**Comment by bnagy** [comment]
The pageheap.cmd script is hardwired to an incorrect path - maybe you could just add the correct gflags command to the docs? Otherwise, could you substitute based on the %cdb% env var you're requiring? I've tried to patch it up, but still no luck...

I'm surprised that this would be pageheap, though, since it's just new followed by delete. Under the debugger, delete doesn't actually seem to invalidate that pointer, which I guess is why it's not crashing. I rebuilt with new VS and debug support to check. Odd.

**Comment by bnagy** [comment]
Derp. OK, I just manually turned on pageheap with +02109870 for the test binary. The UAF now "works", but I am seeing more failures:

```
c:\BugId-master>Tests.py
* Starting tests...
cdb:stderr>R6025
cdb:stderr>- pure virtual function call
- AccessViolation READ 1 =AMD64=> AVR:NULL+X
    => A34E AVR:NULL+ODD Tests_x64.exe!wmain (Access violation while reading memory at 0x1 using a NULL ptr)

c:\BugId-master>Tests.py
* Starting tests...
cdb:stderr>R6025
cdb:stderr>- pure virtual function call
- AccessViolation READ FFFFFFFFFFFFFFFF =AMD64=> AVR:NULL-X
    => A34E AVR:NULL-ODD Tests_x64.exe!wmain (Access violation while reading memory at 0xFFFFFFFFFFFFFFFF using a NULL ptr)
```

**Comment by SkyLined** [comment]
That's my bad: I made some changes to the code to replace +/-X with +/-ODD/EVEN and forgot to include the update to the tests in my commit. It's already fixed, but I haven't uploaded the code and won't be able to do so until next week....

You can manually replace +X with +ODD/+EVEN as needed in tests.py or wait for my commit next week... Sorry about that :S

**Comment by bnagy** [comment]
Confirm - replaced all -X with -ODD and I get a clean pass. Thanks for the help! I will leave this open in case anyone else hits it...

**Comment by SkyLined** [comment]
... And as reminder for me to commit this :) thank you for the feedback,
much appreciated!

**Comment by SkyLined** [comment]
I've updated the documentation to explain the use of pageheap.cmd and gflags.exe. I've also uploaded the fix for the +X/+ODD/+EVEN bug.

The tests.py output leaves some things to be desired and not all tests are working as expected yet. I hope to improve it over time. (Yes, those were errors)
