### ISSUE TITLE
Timezone re.match issue

### ISSUE THREAD

**Issue by asnine** [SkyLined/BugId#25]
File "\BugId\modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py", line 19, in fnGetDebuggerTime
    assert oTimeMatch, "Cannot parse debugger time: %s" % repr(sDebuggerTime);
AssertionError: Cannot parse debugger time: 'Sun Oct  9 01:26:16.841 2016 (UTC - 7:00)'

 r"\(\w+ \+ \d+:\d+\)",                                   # Timezone (don't care).
==>
r"(\(\w+) (\-|\+) (\d+:\d+\))"

**Comment by SkyLined** [comment]
thanks for reporting! That specific issue has already been address about a month ago :) please download the latest version and see if that works better for you!

https://github.com/SkyLined/cBugId/commit/99eb81b90c79798a6de32ff180e39d4e96b3f25f
