### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by vishnuraju** [SkyLined/BugId#27]
UnboundLocalError("local variable 'uMaxCPUProcessId' referenced before assignment",) ..
This was triggered on closing the tested application (IE) with out closing it on the terminal.

**Comment by SkyLined** [comment]
Thank you for the report. I apologize for not responding sooner.

I fixed this issue in https://github.com/SkyLined/cBugId/commit/28885ed3c17581fa62d157c4f7bd319ba6204f6d

Please download the latest version of BugId, and let me know when you still run into this issue.
