### ISSUE TITLE
Add support for Type Confusion Detection

### ISSUE THREAD

**Issue by hacksysteam** [SkyLined/BugId#32]
Hi @SkyLined 

I have an idea of detecting `Heap Based Type Confusion` vulnerabilities.

Suppose: Heap Chunk `UserAddress = 0x41414141` and size is **10** and the crash occurred while dereferencing `[eax + 20]` where `eax = 0x41414141`.

So, the question is why the `OOB Read` occurred as there were no arithmetic done on the pointer. Basically it means that `EAX` was supposed to be `Object A` but got `Object B`.

Thanks.

**Comment by SkyLined** [comment]
Cool idea, but unfortunately I expect there to be many false positives such as this one:

BYTE* pLoopupTable = new BYTE[10]; // Create heap chunk of size 10
BYTE uValue = pLookupTable[20]; // Derefence byte #20

Issues similar to the above example are quite common in real life in my experience, so there would be too many false positives.

I do appreciate your input and any more thoughts you might have on detecting bad casts; it's an area where BugId is not very good at at the moment.
