### ISSUE TITLE
- An internal exception has occured:

### ISSUE THREAD

**Issue by anilaphale** [SkyLined/BugId#35]
Got this error after updating everything to new version i.e.

  BugId version 2017-07-04 16:31
  cBugId version 2017-07-04 14:39
  FileSystem version 2017-05-12 12:04
  Kill version 2017-05-12 12:06
--------------------------------------------------------------------------------
- An internal exception has occured:
  AssertionError('Status messages should not be output when output is redirected.',)
  Stack:
    3 __fOutputHelper (c:\Users\Windows10\Desktop\Edge-DBG-Using\BugId-master\oConsole.py/152)
      > "Status messages should not be output when output is redirected.";
    2 fStatus (c:\Users\Windows10\Desktop\Edge-DBG-Using\BugId-master\oConsole.py/208)
      > oConsole.__fOutputHelper(axCharsAndColors, True);
    1 fuMain (c:\Users\Windows10\Desktop\Edge-DBG-Using\BugId-master\BugId.py/717)
      > oConsole.fStatus("* The debugger is attaching to running processes and starting the application...");
    0 c:\Users\Windows10\Desktop\Edge-DBG-Using\BugId-master\BugId.py/815
      > uExitCode = fuMain(sys.argv[1:]);
  BugId version 2017-07-04 16:31
  cBugId version 2017-07-04 14:39
  FileSystem version 2017-05-12 12:04
  Kill version 2017-05-12 12:06
--------------------------------------------------------------------------------

**Comment by anilaphale** [comment]
After your yesterdays update above error is gone but i have started getting another error:
==========================================================
********************************************************************************
BugId depends on Kill, which you can download at https://github.com/SkyLined/Kill/
********************************************************************************
Traceback (most recent call last):
  File "c:\Users\Windows10\Desktop\Edge-DBG-Using\BugId-master\BugId.py", line 68, in <module>
    from dxConfig import dxConfig;
  File "c:\Users\Windows10\Desktop\Edge-DBG-Using\BugId-master\dxConfig.py", line 56, in <module>
    dxConfig["cBugId"] = cBugId.dxConfig;
AttributeError: type object 'cBugId' has no attribute 'dxConfig'

**Comment by anilaphale** [comment]
issue resolved after updating cBugId as well.

thanks.

**Comment by anilaphale** [comment]
Now getting this issue:



--------------------------------------------------------------------------------
- An internal exception has occured:
  AssertionError("Cannot have two UWP dummy's; something is wrong",)
  Stack:
    1 cCdbWrapper_fCdbStdInOutThread (c:\users\windows10\desktop\edge-dbg-using\bugid-master\modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py/406)
      > "Cannot have two UWP dummy's; something is wrong";
    0 _fThreadWrapper (c:\users\windows10\desktop\edge-dbg-using\bugid-master\modules\cBugId\cCdbWrapper.py/265)
      > fActivity(oCdbWrapper);
  BugId version 2017-07-10 18:50
  cBugId version 2017-07-10 18:15
  FileSystem version unknown
  Kill version unknown
--------------------------------------------------------------------------------

**Comment by SkyLined** [comment]
Can you run again with `--cBugId.bOutputStdIO=true` as in:
```
> BugId --cBugId.bOutputStdIO=true <whatever arguments you normally use>
```

That would give me a lot more information to work with and fix this.

**Comment by SkyLined** [comment]
...or if you download the latest version of BugId and cBugId, you can use `-v` for verbose output, as in:
```
> BugId -v <whatever arguments you normally use>
```

**Comment by anilaphale** [comment]
Issue is solved as i was using outdated EdgeDbg (EdgeBugId.cmd).

So after updating EdgeDbg everything is working fine.

Thanks.
