### ISSUE TITLE
AssertionError: Cannot dump a memory region with its end address x bytes beyond its start address

### ISSUE THREAD

**Issue by soiax** [SkyLined/BugId#39]
Another one:

`--------------------------------------------------------------------------------
- An internal exception has occured:
  AssertionError('Cannot dump a memory region with its end address 0x444A3FF2 1474 bytes beyond its start address 0x444A3A30',)
  Stack:
    3 fAddMemoryDump (.\modules\cBugId\cBugReport.py/69)
      > "Cannot dump a memory region with its end address 0x%X %d bytes beyond its start address 0x%X" % (uEndAddress, uSize, uStartAddress);
    2 foDetectAndCreateBugReportForVERIFIER_STOP (.\modules\cBugId\foDetectAndCreateBugReportForVERIFIER_STOP.py/280)
      > "Memory near heap block at 0x%X" % uMemoryDumpStartAddress,
    1 cCdbWrapper_fCdbStdInOutThread (.\modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py/545)
      > oBugReport = foDetectAndCreateBugReportForVERIFIER_STOP(oCdbWrapper, uExceptionCode, asUnprocessedCdbOutput);
    0 __fThreadWrapper (.\modules\cBugId\cCdbWrapper.py/266)
      > fActivity(oCdbWrapper);
  BugId version 2017-08-25 17:36
  cBugId version 2017-08-25 17:35
  FileSystem version 2017-05-12 12:04
  Kill version 2017-05-12 12:06
--------------------------------------------------------------------------------`

**Comment by SkyLined** [comment]
This bug is similar to #38 in that the memory allocation is larger than what cBugId is designed to handle. I've added code to truncate the memory dump to the most relevant part to prevent this issue.

https://github.com/SkyLined/cBugId/commit/2b5ccddb64aaae01db926f83f6e4813c4b33f57c
