### ISSUE TITLE
AssertionError: Cannot modify virtual allocation protection

### ISSUE THREAD

**Issue by soiax** [SkyLined/BugId#40]
This happens rarely, randomly, and it can't be reproduced with a specific file.

`--------------------------------------------------------------------------------
- An internal exception has occured:
  AssertionError('Cannot modify virtual allocation protection',)
  Stack:
    6 fauGetBytesAtOffset (***\modules\cBugId\cVirtualAllocation.py/179)
      > "Cannot modify virtual allocation protection";
    5 fuGetValueAtOffset (***\modules\cBugId\cVirtualAllocation.py/197)
      > auBytes = oVirtualAllocation.fauGetBytesAtOffset(uOffset, uSize);
    4 foGetForAddress (***\modules\cBugId\cPageHeapAllocation.py/164)
      > uStartStamp = oVirtualAllocation.fuGetValueAtOffset(uStartStampOffset, 4);
    3 cBugReport_foAnalyzeException_STATUS_ACCESS_VIOLATION (***\modules\cBugId\cBugReport_foAnalyzeException_STATUS_ACCESS_VIOLATION.py/210)
      > oPageHeapAllocation = cPageHeapAllocation.foGetForAddress(oProcess, uAccessViolationAddress);
    2 foCreateForException (***\modules\cBugId\cBugReport.py/93)
      > oBugReport = dfoAnalyzeException_by_uExceptionCode[oException.uCode](oBugReport, oProcess, oException);
    1 cCdbWrapper_fCdbStdInOutThread (***\modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py/559)
      > oBugReport = cBugReport.foCreateForException(oCdbWrapper.oCurrentProcess, uExceptionCode, sExceptionDescription, bApplicationCannotHandleException);
    0 __fThreadWrapper (***\modules\cBugId\cCdbWrapper.py/266)
      > fActivity(oCdbWrapper);
  BugId version 2017-08-30 17:10
  cBugId version 2017-08-30 17:05
  FileSystem version 2017-05-12 12:04
  Kill version 2017-05-12 12:06
--------------------------------------------------------------------------------`

**Comment by SkyLined** [comment]
Unfortunately, I cannot say what the root cause is, or reproduce this myself. However, I have added a bit of code that adds the error code returned by Windows to the error. If you can still reproduce the issue with the new code, please copy+paste the error here again, so I can check out the error code reported.

**Comment by soiax** [comment]
I haven't seen this crash since... so i close it.
