### ISSUE TITLE
AssertionError: Unexpected list module output

### ISSUE THREAD

**Issue by soiax** [SkyLined/BugId#41]
--------------------------------------------------------------------------------
- An internal exception has occured:
  AssertionError('Unexpected list module output:     Has CLR image header, track-debug-data flag not set\r\nstart             end
    module name\r\n00000000`00b90000 00000000`00d84000   image00000000_00b90000   (deferred)             \r\n    Image path: image00000000`00b90000\r\n    Image name: image00000000`00b90000\r\n    Has CLR image header, track-debug-data flag not set\r\n    ******
  Stack:
    7 fProcess_lmov_Output (***\modules\cBugId\cModule.py/261)
      > "Unexpected list module output: %s\r\n%s" % (sLine, "\r\n".join(as_lmov_Output));
    6 __foGetOrCreateFrom_lmov (***\modules\cBugId\cModule.py/150)
      > oModule.fProcess_lmov_Output(as_lmov_Output);
    5 foCreateForStartAddress (***\modules\cBugId\cModule.py/131)
      > return cModule.__foGetOrCreateFrom_lmov(oProcess, "a 0x%X;" % uStartAddress);
    4 foGetOrCreateModuleForStartAddress (***\modules\cBugId\cProcess.py/202)
      > return cModule.foCreateForStartAddress(oProcess, uStartAddress);
    3 oMainModule (***\modules\cBugId\cProcess.py/195)
      > oProcess.__oMainModule = oProcess.foGetOrCreateModuleForStartAddress(oProcess.__uMainModuleImageBaseAddress);
    2 sBinaryName (***\modules\cBugId\cProcess.py/52)
      > return oProcess.oMainModule.sBinaryName;
    1 cCdbWrapper_fCdbStdInOutThread (***\modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py/439)
      > "Started process %d/0x%X (%s)." % (uProcessId, uProcessId, oCdbWrapper.oCurrentProcess.sBinaryName),
    0 __fThreadWrapper (***\modules\cBugId\cCdbWrapper.py/266)
      > fActivity(oCdbWrapper);
  BugId version 2017-08-30 17:10
  cBugId version 2017-08-30 17:05
  FileSystem version 2017-05-12 12:04
  Kill version 2017-05-12 12:06
--------------------------------------------------------------------------------

**Comment by SkyLined** [comment]
Sorry for the slow response on this one, I was busy getting a Browser Security white paper out the door in my spare time as I was working on yet another project full time...

Anyway, I finally had some time to look at this and fix it. Thanks for reporting it to me.

**Comment by soiax** [comment]
This still crashes the same way:
`--------------------------------------------------------------------------------
- An internal exception has occured:
  AssertionError('Unexpected list module output:     Has CLR image header, track-debug-data flag not set\r\nstart             end
    module name\r\n00000000`00080000 00000000`00274000   image00000000_00080000   (deferred)             \r\n    Image path: image00000000`00080000\r\n    Image name: image00000000`00080000\r\n    Has CLR image header, track-debug-data flag not set\r\n    Timestamp:        Mon Aug  7 08:43:15 2017 (59880C03)\r\n    CheckSum:         001FA5C1\r\n    ImageSize:        001F4000\r\n    File version:     4.5.6.0\r\n    Product
version:  4.5.6.0\r\n    File flags:       1 (Mask 17) Debug\r\n    File OS:          4 Unknown Win32\r\n    File type:        0.0 Unknown\r\n    File date:        00000000.00000000\r\n    Translations:     0409.04b0\r\n    CompanyName:      Adobe Systems Incorporated\r\n    ProductName:      Adobe Digital Editions 4.5.6\r\n    InternalName:     DigitalEditions\r\n    OriginalFilename: DigitalEditions.exe\r\n    ProductVersion:   4.5.6.0\r\n    FileVersion:      4.5.6.0\r\n    FileDescription:  Adobe Digital Editions 4.5.6\r\n    LegalCopyright:   Copyright \xa9 2006-2017 Adobe Systems Incorporated',)
  Stack:
    7 fProcess_lmov_Output (z:\secprogs\bugidnew\modules\cBugId\cModule.py/260)
      > "Unexpected list module output: %s\r\n%s" % (sLine, "\r\n".join(as_lmov_Output));`

It's adobe digital editions.

**Comment by SkyLined** [comment]
That makes sense: I just new noticed the message that triggers this issue starts with whitespace, as in `    Has CLR image header, track-debug-data flag not set`. This whitespace was removed by the github webpage, so the check I added for this did not detect it correctly. I've created a new check that removes all leading and trailing whitespace before checking, so this problem should now be fixed correctly. Please give it a try and let me know if the problem persists.

**Comment by soiax** [comment]
Yes, it looks fixed now, thanks.
