### ISSUE TITLE
WindowsError(5, 'Access is denied')

### ISSUE THREAD

**Issue by sudhackar** [SkyLined/BugId#43]
Hi

While running BugId with foxit I encountered an error which persisted with different inputs and even in fresh VM installations. 

Here I have attached the  `--verbose` output from a dummy input.

* Applying application specific configuration for foxit:
  + Changed config setting bApplicationTerminatesWithMainProcess from False to True.
  + Changed config setting cBugId.nExcessiveCPUUsageWormRunTime from 1 to 0.5.
  + Changed config setting nExcessiveCPUUsageCheckInitialTimeout from 5 to 10.0.
  + Changed config setting nApplicationMaxRunTime from None to 10.0.
  + Changed config setting cBugId.nExcessiveCPUUsagePercent from 90 to 75.
  + Changed config setting cBugId.nExcessiveCPUUsageCheckInterval from 10.0 to 5.0.

* Command line: C:\Program Files\Foxit Software\Foxit Reader\FoxitReader.exe C:\Users\IEUser\Desktop\alp99.pdf

stdout>
stdout>Microsoft (R) Windows Debugger Version 10.0.15063.468 X86
stdout>Copyright (c) Microsoft Corporation. All rights reserved.
stdout>
stdout>CommandLine: "C:\Program Files\Foxit Software\Foxit Reader\FoxitReader.exe" C:\Users\IEUser\Desktop\alp99.pdf
stdout>
stdout>************* Symbol Path validation summary **************
stdout>Response                         Time (ms)     Location
stdout>Deferred                                       cache*
stdout>Deferred                                       srv*http://msdl.microsoft.com/download/symbols
stdout>Symbol search path is: cache*;srv*http://msdl.microsoft.com/download/symbols
stdout>Executable search path is: 
stdout>ModLoad: 01290000 047e0000   FoxitReader_Lib_Full.exe
stdout>ModLoad: 76f50000 7708c000   ntdll.dll
stdout>ModLoad: 69c40000 69ca0000   C:\Windows\system32\verifier.dll
stdout>Page heap: pid 0xD3C: page heap enabled with flags 0x3.
stdout>ModLoad: 75a50000 75b24000   C:\Windows\system32\kernel32.dll
stdout>ModLoad: 750f0000 7513b000   C:\Windows\system32\KERNELBASE.dll
stdout>ModLoad: 754d0000 75599000   C:\Windows\system32\USER32.dll
stdout>ModLoad: 76140000 7618e000   C:\Windows\system32\GDI32.dll
stdout>ModLoad: 77170000 7717a000   C:\Windows\system32\LPK.dll
stdout>ModLoad: 75c70000 75d0d000   C:\Windows\system32\USP10.dll
stdout>ModLoad: 759a0000 75a4c000   C:\Windows\system32\msvcrt.dll
stdout>ModLoad: 73570000 73575000   C:\Windows\system32\MSIMG32.dll
stdout>ModLoad: 76ed0000 76f4b000   C:\Windows\system32\COMDLG32.dll
stdout>ModLoad: 770c0000 77117000   C:\Windows\system32\SHLWAPI.dll
stdout>ModLoad: 73e00000 73f9e000   C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_41e6975e2bd6f2b2\COMCTL32.dll
stdout>ModLoad: 76220000 76e6a000   C:\Windows\system32\SHELL32.dll
stdout>ModLoad: 70430000 70481000   C:\Windows\system32\WINSPOOL.DRV
stdout>ModLoad: 757a0000 75840000   C:\Windows\system32\ADVAPI32.dll
stdout>ModLoad: 75c50000 75c69000   C:\Windows\SYSTEM32\sechost.dll
stdout>ModLoad: 75420000 754c2000   C:\Windows\system32\RPCRT4.dll
stdout>ModLoad: 75840000 7599c000   C:\Windows\system32\ole32.dll
stdout>ModLoad: 76190000 7621f000   C:\Windows\system32\OLEAUT32.dll
stdout>ModLoad: 6ab80000 6ab9c000   C:\Windows\system32\oledlg.dll
stdout>ModLoad: 755c0000 7570a000   C:\Windows\system32\urlmon.dll
stdout>ModLoad: 75230000 75234000   C:\Windows\system32\api-ms-win-downlevel-ole32-l1-1-0.dll
stdout>ModLoad: 74f70000 74f74000   C:\Windows\system32\api-ms-win-downlevel-shlwapi-l1-1-0.dll
stdout>ModLoad: 74fc0000 74fc5000   C:\Windows\system32\api-ms-win-downlevel-advapi32-l1-1-0.dll
stdout>ModLoad: 751e0000 751e4000   C:\Windows\system32\api-ms-win-downlevel-user32-l1-1-0.dll
stdout>ModLoad: 74f80000 74f84000   C:\Windows\system32\api-ms-win-downlevel-version-l1-1-0.dll
stdout>ModLoad: 744f0000 744f9000   C:\Windows\system32\version.DLL
stdout>ModLoad: 75140000 75143000   C:\Windows\system32\api-ms-win-downlevel-normaliz-l1-1-0.dll
stdout>ModLoad: 75270000 75273000   C:\Windows\system32\normaliz.DLL
stdout>ModLoad: 75d20000 75f52000   C:\Windows\system32\iertutil.dll
stdout>ModLoad: 75f60000 76136000   C:\Windows\system32\WININET.dll
stdout>ModLoad: 75210000 75227000   C:\Windows\system32\USERENV.dll
stdout>ModLoad: 74f60000 74f6b000   C:\Windows\system32\profapi.dll
stdout>ModLoad: 74f90000 74fbe000   C:\Windows\system32\WINTRUST.dll
stdout>ModLoad: 74fd0000 750f0000   C:\Windows\system32\CRYPT32.dll
stdout>ModLoad: 74f50000 74f5c000   C:\Windows\system32\MSASN1.dll
stdout>ModLoad: 72120000 72127000   C:\Windows\system32\WSOCK32.dll
stdout>ModLoad: 75b40000 75b75000   C:\Windows\system32\WS2_32.dll
stdout>ModLoad: 75d10000 75d16000   C:\Windows\system32\NSI.dll
stdout>ModLoad: 69bc0000 69bfc000   C:\Windows\system32\OLEACC.dll
stdout>ModLoad: 6f390000 6f3c2000   C:\Windows\system32\WINMM.dll
stdout>ModLoad: 73af0000 73c80000   C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.18455_none_72d576ad8665e853\gdiplus.dll
stdout>ModLoad: 744d0000 744ec000   C:\Windows\system32\iphlpapi.dll
stdout>ModLoad: 744c0000 744c7000   C:\Windows\system32\WINNSI.DLL
stdout>ModLoad: 71450000 714a8000   C:\Windows\system32\WINHTTP.dll
stdout>ModLoad: 71400000 7144f000   C:\Windows\system32\webio.dll
stdout>ModLoad: 755a0000 755bf000   C:\Windows\system32\IMM32.dll
stdout>ModLoad: 75b80000 75c4c000   C:\Windows\system32\MSCTF.dll
stdout>ModLoad: 70300000 70312000   C:\Windows\system32\MPR.dll
stdout>ModLoad: 6e980000 6ebc5000   C:\Windows\system32\msi.dll
stdout>ModLoad: 75b30000 75b35000   C:\Windows\system32\PSAPI.DLL
stdout>ModLoad: 736e0000 736f1000   C:\Windows\system32\NETAPI32.dll
stdout>ModLoad: 736d0000 736d9000   C:\Windows\system32\netutils.dll
stdout>ModLoad: 74d40000 74d59000   C:\Windows\system32\srvcli.dll
stdout>ModLoad: 736c0000 736cf000   C:\Windows\system32\wkscli.dll
stdout>ModLoad: 67f60000 67fec000   C:\Windows\system32\ODBC32.dll
stdout>ModLoad: 6a8c0000 6a8e1000   C:\Windows\system32\MSVFW32.dll
stdout>(d3c.dbc): Break instruction exception - code 80000003 (first chance)
stdout>eax=00000000 ebx=00000000 ecx=002efa58 edx=76f970f4 esi=fffffffe edi=00000000
stdout>eip=76ff05a6 esp=002efa74 ebp=002efaa0 iopl=0         nv up ei pl zr na pe nc
stdout>cs=001b  ss=0023  ds=0023  es=0023  fs=003b  gs=0000             efl=00000246
stdout>ntdll!LdrpDoDebuggerBreak+0x2c:
stdout>76ff05a6 cc              int     3
stdout>0:000> 
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .prompt_allow -dis -ea -reg -src -sym; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Display only the prompt
stdout><[{
stdout>Allow the following information to be displayed at the prompt:
stdout>(Other settings can affect whether the information is actually displayed)
stdout>  None
stdout>Do not allow the following information to be displayed at the prompt:
stdout>   sym - Symbol for current instruction
stdout>   dis - Disassembly of current instruction
stdout>    ea - Effective address for current instruction
stdout>   reg - Register state
stdout>   src - Source info for current instruction
stdout>}]>
stdout>0:000> 
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .pcmd -s ".echo;"; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Output a CRLF after running the application
stdout><[{
stdout>Set prompt command
stdout>Per-prompt command is '.echo;'
stdout>}]>
stdout>0:000> 
<stdin< 
stdout>0:000> 
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .lastevent; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get information about last event
stdout><[{
stdout>Last event: d3c.dbc: Break instruction exception - code 80000003 (first chance)
stdout>  debugger time: Fri Sep 22 04:34:35.523 2017 (UTC - 7:00)
stdout>}]>
stdout>0:000> 
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ !peb; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get current proces environment block
stdout><[{
stdout>PEB at 7ffdc000
stdout>    InheritedAddressSpace:    No
stdout>    ReadImageFileExecOptions: No
stdout>    BeingDebugged:            Yes
stdout>    ImageBaseAddress:         01290000
stdout>    Ldr                       77027880
stdout>    Ldr.Initialized:          Yes
stdout>    Ldr.InInitializationOrderModuleList: 00071f98 . 0066cf98
stdout>    Ldr.InLoadOrderModuleList:           0006ff88 . 0066cf88
stdout>    Ldr.InMemoryOrderModuleList:         0006ff90 . 0066cf90
stdout>            Base TimeStamp                     Module
stdout>         1290000 599fd9c5 Aug 25 01:03:17 2017 C:\Program Files\Foxit Software\Foxit Reader\FoxitReader.exe
stdout>        76f50000 521ea91c Aug 28 18:51:24 2013 C:\Windows\SYSTEM32\ntdll.dll
stdout>        69c40000 4a5bdb2a Jul 13 18:11:06 2009 C:\Windows\system32\verifier.dll
stdout>        75a50000 531599f5 Mar 04 01:16:37 2014 C:\Windows\system32\kernel32.dll
stdout>        750f0000 531599f6 Mar 04 01:16:38 2014 C:\Windows\system32\KERNELBASE.dll
stdout>        754d0000 4ce7ba26 Nov 20 04:08:06 2010 C:\Windows\system32\USER32.dll
stdout>        76140000 53f7f199 Aug 22 18:42:49 2014 C:\Windows\system32\GDI32.dll
stdout>        77170000 51b0158a Jun 05 21:52:26 2013 C:\Windows\system32\LPK.dll
stdout>        75c70000 5359c2c9 Apr 24 19:04:57 2014 C:\Windows\system32\USP10.dll
stdout>        759a0000 4eeaf722 Dec 15 23:45:38 2011 C:\Windows\system32\msvcrt.dll
stdout>        73570000 4a5bdaa0 Jul 13 18:08:48 2009 C:\Windows\system32\MSIMG32.dll
stdout>        76ed0000 4ce7b82d Nov 20 03:59:41 2010 C:\Windows\system32\COMDLG32.dll
stdout>        770c0000 4ce7b9e2 Nov 20 04:06:58 2010 C:\Windows\system32\SHLWAPI.dll
stdout>        73e00000 4ce7b71c Nov 20 03:55:08 2010 C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_41e6975e2bd6f2b2\COMCTL32.dll
stdout>        76220000 5330e506 Mar 24 19:08:06 2014 C:\Windows\system32\SHELL32.dll
stdout>        70430000 4ce7ba4b Nov 20 04:08:43 2010 C:\Windows\system32\WINSPOOL.DRV
stdout>        757a0000 521ea86a Aug 28 18:48:26 2013 C:\Windows\system32\ADVAPI32.dll
stdout>        75c50000 4a5bdb04 Jul 13 18:10:28 2009 C:\Windows\SYSTEM32\sechost.dll
stdout>        75420000 53c334f3 Jul 13 18:40:03 2014 C:\Windows\system32\RPCRT4.dll
stdout>        75840000 4ce7b96f Nov 20 04:05:03 2010 C:\Windows\system32\ole32.dll
stdout>        76190000 5441c30c Oct 17 18:31:56 2014 C:\Windows\system32\OLEAUT32.dll
stdout>        6ab80000 4a5bdace Jul 13 18:09:34 2009 C:\Windows\system32\oledlg.dll
stdout>        755c0000 545ad36d Nov 05 17:48:29 2014 C:\Windows\system32\urlmon.dll
stdout>        75230000 50f322ec Jan 13 13:11:08 2013 C:\Windows\system32\api-ms-win-downlevel-ole32-l1-1-0.dll
stdout>        74f70000 50f3244f Jan 13 13:17:03 2013 C:\Windows\system32\api-ms-win-downlevel-shlwapi-l1-1-0.dll
stdout>        74fc0000 50f3243a Jan 13 13:16:42 2013 C:\Windows\system32\api-ms-win-downlevel-advapi32-l1-1-0.dll
stdout>        751e0000 50f322f9 Jan 13 13:11:21 2013 C:\Windows\system32\api-ms-win-downlevel-user32-l1-1-0.dll
stdout>        74f80000 50f322eb Jan 13 13:11:07 2013 C:\Windows\system32\api-ms-win-downlevel-version-l1-1-0.dll
stdout>        744f0000 4a5bdb2b Jul 13 18:11:07 2009 C:\Windows\system32\version.DLL
stdout>        75140000 50f3244e Jan 13 13:17:02 2013 C:\Windows\system32\api-ms-win-downlevel-normaliz-l1-1-0.dll
stdout>        75270000 4a5bdad4 Jul 13 18:09:40 2009 C:\Windows\system32\normaliz.DLL
stdout>        75d20000 545ae56b Nov 05 19:05:15 2014 C:\Windows\system32\iertutil.dll
stdout>        75f60000 545ad456 Nov 05 17:52:22 2014 C:\Windows\system32\WININET.dll
stdout>        75210000 4ce7ba28 Nov 20 04:08:08 2010 C:\Windows\system32\USERENV.dll
stdout>        74f60000 4a5bbf41 Jul 13 16:12:01 2009 C:\Windows\system32\profapi.dll
stdout>        74f90000 51db9720 Jul 08 21:52:48 2013 C:\Windows\system32\WINTRUST.dll
stdout>        74fd0000 52506fc6 Oct 05 13:00:06 2013 C:\Windows\system32\CRYPT32.dll
stdout>        74f50000 4ce7b8c9 Nov 20 04:02:17 2010 C:\Windows\system32\MSASN1.dll
stdout>        72120000 4a5bdb63 Jul 13 18:12:03 2009 C:\Windows\system32\WSOCK32.dll
stdout>        75b40000 4ce7ba68 Nov 20 04:09:12 2010 C:\Windows\system32\WS2_32.dll
stdout>        75d10000 4a5bdad9 Jul 13 18:09:45 2009 C:\Windows\system32\NSI.dll
stdout>        69bc0000 4e587028 Aug 26 21:18:48 2011 C:\Windows\system32\OLEACC.dll
stdout>        6f390000 4ce7ba42 Nov 20 04:08:34 2010 C:\Windows\system32\WINMM.dll
stdout>        73af0000 535b14fb Apr 25 19:07:55 2014 C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.18455_none_72d576ad8665e853\gdiplus.dll
stdout>        744d0000 4ce7b859 Nov 20 04:00:25 2010 C:\Windows\system32\iphlpapi.dll
stdout>        744c0000 4a5bdb43 Jul 13 18:11:31 2009 C:\Windows\system32\WINNSI.DLL
stdout>        71450000 4ce7ba3e Nov 20 04:08:30 2010 C:\Windows\system32\WINHTTP.dll
stdout>        71400000 4ec49b76 Nov 16 21:28:22 2011 C:\Windows\system32\webio.dll
stdout>        755a0000 4ce7b845 Nov 20 04:00:05 2010 C:\Windows\system32\IMM32.dll
stdout>        75b80000 4a5bda69 Jul 13 18:07:53 2009 C:\Windows\system32\MSCTF.dll
stdout>        70300000 4a5bda36 Jul 13 18:07:02 2009 C:\Windows\system32\MPR.dll
stdout>        6e980000 538d9534 Jun 03 02:28:20 2014 C:\Windows\system32\msi.dll
stdout>        75b30000 4a5bdace Jul 13 18:09:34 2009 C:\Windows\system32\PSAPI.DLL
stdout>        736e0000 4ff4b0f6 Jul 04 14:09:10 2012 C:\Windows\system32\NETAPI32.dll
stdout>        736d0000 4ce795a6 Nov 20 01:32:22 2010 C:\Windows\system32\netutils.dll
stdout>        74d40000 4ce7ba1f Nov 20 04:07:59 2010 C:\Windows\system32\srvcli.dll
stdout>        736c0000 4ce795a7 Nov 20 01:32:23 2010 C:\Windows\system32\wkscli.dll
stdout>        67f60000 4ce7b964 Nov 20 04:04:52 2010 C:\Windows\system32\ODBC32.dll
stdout>        6a8c0000 4ce7b8e3 Nov 20 04:02:43 2010 C:\Windows\system32\MSVFW32.dll
stdout>    SubSystemData:     00000000
stdout>    ProcessHeap:       00060000
stdout>    ProcessParameters: 00069780
stdout>    CurrentDirectory:  'C:\Users\IEUser\Desktop\BugId\'
stdout>    WindowTitle:  'C:\Program Files\Foxit Software\Foxit Reader\FoxitReader.exe'
stdout>    ImageFile:    'C:\Program Files\Foxit Software\Foxit Reader\FoxitReader.exe'
stdout>    CommandLine:  '"C:\Program Files\Foxit Software\Foxit Reader\FoxitReader.exe" C:\Users\IEUser\Desktop\alp99.pdf'
stdout>    DllPath:      'C:\Program Files\Foxit Software\Foxit Reader;;C:\Windows\system32;C:\Windows\system;C:\Windows;.;C:\Program Files\Windows Kits\10\Debuggers\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Python27\'
stdout>    Environment:  00067490
stdout>        =::=::\
stdout>        =C:=C:\Users\IEUser\Desktop\BugId
stdout>        ALLUSERSPROFILE=C:\ProgramData
stdout>        APPDATA=C:\Users\IEUser\AppData\Roaming
stdout>        CommonProgramFiles=C:\Program Files\Common Files
stdout>        COMPUTERNAME=IE11WIN7
stdout>        ComSpec=C:\Windows\system32\cmd.exe
stdout>        FP_NO_HOST_CHECK=NO
stdout>        HOMEDRIVE=C:
stdout>        HOMEPATH=\Users\IEUser
stdout>        LOCALAPPDATA=C:\Users\IEUser\AppData\Local
stdout>        LOGONSERVER=\\IE11WIN7
stdout>        MpConfig_ProductAppDataPath=C:\ProgramData\Microsoft\Windows Defender
stdout>        MpConfig_ProductCodeName=AntiSpyware
stdout>        MpConfig_ProductPath=C:\Program Files\Windows Defender
stdout>        MpConfig_ProductUserAppDataPath=C:\Users\IEUser\AppData\Local\Microsoft\Windows Defender
stdout>        MpConfig_ReportingGUID=89687C42-ABBB-F007-BE98-6B4119C36E93
stdout>        NUMBER_OF_PROCESSORS=1
stdout>        OS=Windows_NT
stdout>        Path=C:\Program Files\Windows Kits\10\Debuggers\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Python27\
stdout>        PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
stdout>        PROCESSOR_ARCHITECTURE=x86
stdout>        PROCESSOR_IDENTIFIER=x86 Family 6 Model 37 Stepping 2, GenuineIntel
stdout>        PROCESSOR_LEVEL=6
stdout>        PROCESSOR_REVISION=2502
stdout>        ProgramData=C:\ProgramData
stdout>        ProgramFiles=C:\Program Files
stdout>        PROMPT=$P$G
stdout>        PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
stdout>        PUBLIC=C:\Users\Public
stdout>        PYTHON="C:\Python27\python.exe"
stdout>        SESSIONNAME=Console
stdout>        SystemDrive=C:
stdout>        SystemRoot=C:\Windows
stdout>        TEMP=C:\Users\IEUser\AppData\Local\Temp
stdout>        TMP=C:\Users\IEUser\AppData\Local\Temp
stdout>        USERDOMAIN=IE11WIN7
stdout>        USERNAME=IEUser
stdout>        USERPROFILE=C:\Users\IEUser
stdout>        windir=C:\Windows
stdout>}]>
stdout>0:000> 
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ lmov a 0x1290000; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get module information
stdout><[{
stdout>start    end        module name
stdout>01290000 047e0000   FoxitReader_Lib_Full   (deferred)             
stdout>    Image path: FoxitReader_Lib_Full.exe
stdout>    Image name: FoxitReader_Lib_Full.exe
stdout>    Timestamp:        Fri Aug 25 01:03:17 2017 (599FD9C5)
stdout>    CheckSum:         034D9FB0
stdout>    ImageSize:        03550000
stdout>    File version:     8.3.2.25013
stdout>    Product version:  8.3.2.25013
stdout>    File flags:       0 (Mask 3F)
stdout>    File OS:          4 Unknown Win32
stdout>    File type:        1.0 App
stdout>    File date:        00000000.00000000
stdout>    Translations:     0000.04b0
stdout>    CompanyName:      Foxit Software Inc.
stdout>    ProductName:      Foxit Reader
stdout>    InternalName:     Foxit Reader.exe
stdout>    OriginalFilename: Foxit Reader.EXE
stdout>    ProductVersion:   8.3.2.25013
stdout>    FileVersion:      8.3.2.25013
stdout>    PrivateBuild:     8.3.2.25013
stdout>    SpecialBuild:     8.3.2.25013
stdout>    FileDescription:  Foxit Reader 8.3
stdout>    LegalCopyright:   Copyright © 2004-2017 Foxit Software Inc. All Rights Reserved. 
stdout>    LegalTrademarks:  Copyright © 2004-2017 Foxit Software Inc. All Rights Reserved. 
stdout>    Comments:         Copyright © 2004-2017 Foxit Software Inc. All Rights Reserved. 
stdout>}]>
stdout>0:000> 
* New process 3388/0xD3C: foxitreader_lib_full.exe
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .childdbg 1; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Debug child processes
stdout><[{
stdout>Processes created by the current process will be debugged
stdout>}]>
stdout>0:000> 
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ sxd *;sxi ld;sxi ud;sxd 0xC0000094;sxd 0xC0000095;sxd 0xC0000008;sxd 0xC0000235;sxd 0x80000004;sxd 0x4000001E;sxd 0xE06D7363;sxd 0x40080201;sxd 0x40080202;sxe cpr;sxe ibp;sxe epr;sxe aph;sxe 0xC0000005;sxe 0xC0000420;sxe 0x80000003;sxe 0xC000008C;sxe 0x80000002;sxe 0xC0000602;sxe 0x80000001;sxe 0xC000001D;sxe 0xC0000006;sxe 0xC0000096;sxe 0xC0000409;sxe 0xC00000FD;sxe 0x4000001F;sxe 0x80000007; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Setup exception handling
stdout><[{
stdout>}]>
stdout>0:000> 
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .time; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get debugger time
stdout><[{
stdout>Debug session time: Fri Sep 22 04:34:35.794 2017 (UTC - 7:00)
stdout>System Uptime: 0 days 1:00:01.858
stdout>Process Uptime: 0 days 0:00:00.360
stdout>  Kernel time: 0 days 0:00:00.040
stdout>  User time: 0 days 0:00:00.010
stdout>}]>
stdout>0:000> 
<stdin<gn;
stdout>(d3c.22c): C++ EH exception - code e06d7363 (first chance)
stdout>(d3c.22c): C++ EH exception - code e06d7363 (first chance)
stdout>(d3c.22c): C++ EH exception - code e06d7363 (first chance)
stdout>StopRequest(d3c.904): Break instruction exception - code 80000003 (first chance)
stdout>
stdout>0:007> 
<stdin< 
stdout>0:007> 
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .lastevent; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get information about last event
stdout><[{
stdout>Last event: d3c.904: Break instruction exception - code 80000003 (first chance)
stdout>  debugger time: Fri Sep 22 04:34:45.808 2017 (UTC - 7:00)
stdout>}]>
stdout>0:007> 
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .exr -1; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get exception record
stdout><[{
stdout>ExceptionAddress: 76f84108 (ntdll!DbgBreakPoint)
stdout>   ExceptionCode: 80000003 (Break instruction exception)
stdout>  ExceptionFlags: 00000000
stdout>NumberParameters: 3
stdout>   Parameter[0]: 00000000
stdout>   Parameter[1]: 8501d968
stdout>   Parameter[2]: 76fef1d3
stdout>}]>
stdout>0:007> 
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ lmov m ntdll; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get module information
stdout><[{
stdout>start    end        module name
stdout>76f50000 7708c000   ntdll      (pdb symbols)          C:\Program Files\Windows Kits\10\Debuggers\x86\sym\ntdll.pdb\CD4062A231154A17A18DAE7D1A0FBACC2\ntdll.pdb
stdout>    Loaded symbol image file: C:\Windows\SYSTEM32\ntdll.dll
stdout>    Image path: ntdll.dll
stdout>    Image name: ntdll.dll
stdout>    Timestamp:        Wed Aug 28 18:51:24 2013 (521EA91C)
stdout>    CheckSum:         00141148
stdout>    ImageSize:        0013C000
stdout>    File version:     6.1.7601.18247
stdout>    Product version:  6.1.7601.18247
stdout>    File flags:       0 (Mask 3F)
stdout>    File OS:          40004 NT Win32
stdout>    File type:        2.0 Dll
stdout>    File date:        00000000.00000000
stdout>    Translations:     0409.04b0
stdout>    CompanyName:      Microsoft Corporation
stdout>    ProductName:      Microsoft® Windows® Operating System
stdout>    InternalName:     ntdll.dll
stdout>    OriginalFilename: ntdll.dll
stdout>    ProductVersion:   6.1.7601.18247
stdout>    FileVersion:      6.1.7601.18247 (win7sp1_gdr.130828-1532)
stdout>    FileDescription:  NT Layer DLL
stdout>    LegalCopyright:   © Microsoft Corporation. All rights reserved.
stdout>}]>
stdout>0:007> 
+ T+10.0 The application has been running for 10.0 seconds without crashing.

<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .time; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get debugger time
--------------------------------------------------------------------------------
- An internal exception has occured:
  WindowsError(5, 'Access is denied')
  Stack:
    4 _execute_child (C:\Python27\lib\subprocess.py/640)
      > startupinfo)
    3 __init__ (C:\Python27\lib\subprocess.py/390)
      > errread, errwrite)
    2 fKillProcessesUntilTheyAreDead (c:\users\ieuser\desktop\bugid\modules\Kill\fKillProcessesUntilTheyAreDead.py/15)
      > oKillProcess = subprocess.Popen(asKillCommand, stdout=subprocess.PIPE, stderr=subprocess.PIPE);
    1 cCdbWrapper_fCdbCleanupThread (c:\users\ieuser\desktop\bugid\modules\cBugId\cCdbWrapper_fCdbCleanupThread.py/38)
      > Kill.fKillProcessesUntilTheyAreDead(oCdbWrapper.doProcess_by_uId.keys());
    0 __fThreadWrapper (c:\users\ieuser\desktop\bugid\modules\cBugId\cCdbWrapper.py/262)
      > fActivity(oCdbWrapper);
  BugId version 2017-09-18 16:24
  cBugId version 2017-09-18 14:28
  FileSystem version 2017-05-12 12:04
  Kill version 2017-05-12 12:06
--------------------------------------------------------------------------------

Please report the above details at the below web-page so it can be addressed:
    https://github.com/SkyLined/BugId/issues/new
If you do not have a github account, or you want to report this issue
privately, you can also send an email to:
    BugId@skylined.nl

In your report, please copy the information about the exception reported
above, as well as the stack trace and BugId version information. This makes
it easier to determine the cause of this issue and makes for faster fixes.

If you can reproduce the issue, it would help a lot if you can run BugId in
verbose mode by adding the --verbose command-line argument.
as in:BugId -v --verbose foxit -- C:\Users\IEUser\Desktop\alp99.pdf

Thank you in advance for helping to improve BugId!

**Comment by sudhackar** [comment]
Looks like using git from Cygwin somehow messed up with the directory permissions. To those who are facing such an error try cloning normally.

**Comment by SkyLined** [comment]
I have seen this issue before myself when I checked out `Kill` on a Linux system, and then ran it from a SMB share on a Windows system. Git will not set the execute flag on `Kill_*.exe` binaries, and Windows will honor this, which results in an `Access denied` error when BugId tries to execute them (the same is true for DLLs btw).

Setting the `x` flag on the `Kill_*.exe` will also resolve this issue.

Finally, I have plans to replace the `Kill_*.exe` binaries with direct Windows API calls from Python, which would simplify things and prevent this error from ever happening. However, I have no time frame for that at this point.
