### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by bpavesi** [SkyLined/BugId#44]
when i start bugid for IE11 64 i get the following assertion:

C:\Users\xxx\Downloads\BugId-master (1)\BugId-master>python BugId.py @msie64
Traceback (most recent call last):
  File "BugId.py", line 119, in <module>
    "-profile", mFileSystem.fs83Path(sFirefoxProfilePath),
  File "C:\Users\xxx\Downloads\BugId-master (1)\BugId-master\modules\mFileSystem\FileSystem.py", line 87, in fs83Path
    "GetShortPathNameW('...', NULL, 0) => Error 0x%08X" % KERNEL32.GetLastError();
AssertionError: GetShortPathNameW('...', NULL, 0) => Error 0x00000002

**Comment by SkyLined** [comment]
Thank you for reporting and sorry to hear that. I won't be able to fix this until a week from now. You should be able to remove that line (119) from BugId.py and debug MSIE as the code is related to Firefox.

**Comment by bpavesi** [comment]
it works! 
tnx

**Comment by SkyLined** [comment]
This issue has been fixed. You should be able to use the latest version without modifications.
