### ISSUE TITLE
bugid.py --version not working

### ISSUE THREAD

**Issue by soiax** [SkyLined/BugId#46]
`
h:\bugidnew>BugId.py --version
- An internal exception has occured:
  AttributeError("'cConsole' object has no attribute 'oVersionInformation'",)
  Stack:
    2 fVersionCheck (H:\bugidnew\fVersionCheck.py/15)
      > ("oConsole",          "oConsole",           oConsole.oVersionInformation),
    1 fuMain (H:\secprogs\bugidnew\BugId.py/589)
      > fVersionCheck();
    0 H:\secprogs\bugidnew\BugId.py/881
      > uExitCode = fuMain(sys.argv[1:]);

  Windows version: Windows 10 Pro release 1607, build 14393
  BugId version: 2017-10-25 10:01
  cBugId version: 2017-11-01 16:21
  mFileSystem version: 2017-11-01 16:16
  mWindowsAPI version: 2017-11-01 16:15
Traceback (most recent call last):
  File "H:\bugidnew\BugId.py", line 895, in <module>
    fDumpExceptionAndExit(oException, oTraceBack);
  File "H:\bugidnew\fDumpExceptionAndExit.py", line 33, in fDumpExceptionAndExit
    oConsole.fPrint(ERROR,"  ", sModule, " version: ", xModule.oVersionInformation.sCurrentVersion);
AttributeError: 'cConsole' object has no attribute 'oVersionInformation'

H:\bugidnew>`

**Comment by kkuehl** [comment]
This seems to be working fine for me with oConsole version: 2017-11-01 16:15

**Comment by SkyLined** [comment]
Sorry for the slow response. As @kkuehl suggested, that bug has been fixed in a newer version of oConsole. Please update to the latest.

**Comment by soiax** [comment]
Hmm ... yeah it works with a fresh clone.

I just updated with git pull, (git submodule init), git submodule update all the time.... and it looks like it has the latest oConsole but still gave this error... so git messed up something :P
