### ISSUE TITLE
BugId can no longer start a process from a binary path containing space.

### ISSUE THREAD

**Issue by kkuehl** [SkyLined/BugId#48]
When attempting to add support to pass --sDefaultBrowserTestURL from the command line with the following small patch:
```
C:\Users\kkuehl\Downloads\BugId>git diff
diff --git a/BugId.py b/BugId.py
index 7ebe72a..c94ddb9 100644
--- a/BugId.py
+++ b/BugId.py
@@ -632,6 +632,8 @@ def fuMain(asArguments):
           oConsole.fPrint(ERROR, "- You must specify \"true\" or \"false\" for ", ERROR_INFO, "--", sSettingName);
       elif sSettingName in ["test-internal-error", "internal-error-test"]:
         raise Exception("Testing internal error");
+      elif sSettingName in ["sDefaultBrowserTestURL"]:
+        asApplicationOptionalArguments = [sValue]
       else:
         try:
           xValue = json.loads(sValue);
```
I received the following error:
C:\Users\kkuehl\Downloads\BugId>python ./BugId.py "C:\Program Files\Internet Explorer\iexplore.exe" --nApplicationMaxRunTime=10 --sDefaultBrowserTestURL=http://www.google.com
* Command line: C:\Program Files\Internet Explorer\iexplore.exe http://www.google.com
--------------------------------------------------------------------------------
- An internal exception has occured:
  AssertionError('End-of-command-output marker missing:\r\nCommandLine: C:\\Program Files\\Internet Explorer\\iexplore.exe\r\nCreate will proceed with next execution\r\n                                                                  ^ Extra character error in \' .create "C:\\Program Files\\Internet Explorer\\iexplore.exe\'',)
  Stack:
    3 cCdbWrapper_fasExecuteCdbCommand (C:\Users\kkuehl\Downloads\cBugId\cCdbWrapper_fasExecuteCdbCommand.py/84)
      > "End-of-command-output marker missing:\r\n%s" % "\r\n".join(oEndOfCommandOutputMarkerMissingException.asCommandOutput);
    2 fasExecuteCdbCommand (C:\Users\kkuehl\Downloads\cBugId\cCdbWrapper.py/411)
      > return cCdbWrapper_fasExecuteCdbCommand(oCdbWrapper, *axArguments, **dxArguments);
    1 cCdbWrapper_fCdbStdInOutThread (C:\Users\kkuehl\Downloads\cBugId\cCdbWrapper_fCdbStdInOutThread.py/191)
      > sComment = "Start application command",
    0 __fThreadWrapper (C:\Users\kkuehl\Downloads\cBugId\cCdbWrapper.py/261)
      > fActivity(oCdbWrapper);

  Windows version: Windows 10 Pro release 1703, build 15063
  BugId version: 2017-11-21 16:04
  cBugId version: 2017-11-21 16:02
  mFileSystem version: 2017-11-11 10:13
  mWindowsAPI version: 2017-11-21 12:32
  oConsole version: 2017-11-21 15:58
--------------------------------------------------------------------------------

Please report the above details at the below web-page so it can be addressed:

This diff also fails with the same backtrace:
```
C:\Users\kkuehl\Downloads\BugId>git diff
diff --git a/BugId.py b/BugId.py
index 7ebe72a..d48d3f1 100644
--- a/BugId.py
+++ b/BugId.py
@@ -516,7 +516,7 @@ def fNewProcessHandler(oBugId, uProcessId, sBinaryName, sCommandLine):
   if gasAttachToProcessesForExecutableNames:
     oBugId.fAttachToProcessesForExecutableNames(*gasAttachToProcessesForExecutableNames);

-def fuMain(asArguments):
+def fuMain(asArguments, url):
   global gbVerbose, gbQuiet, gasAttachToProcessesForExecutableNames;
   if len(asArguments) == 0:
     fPrintLogo();
@@ -528,7 +528,7 @@ def fuMain(asArguments):
   auApplicationProcessIds = [];
   sUWPApplicationPackageName = None;
   sUWPApplicationId = None;
-  asApplicationOptionalArguments = None;
+  asApplicationOptionalArguments = url;
   sApplicationISA = None;
   bRepeat = False;
   bCheckForUpdates = False;
@@ -896,7 +896,8 @@ def fuMain(asArguments):

 if __name__ == "__main__":
   try:
-    uExitCode = fuMain(sys.argv[1:]);
+    # My personal project passes a url as a single item list here.
+    uExitCode = fuMain(sys.argv[1:], ['http://www.google.com']);

     if not gbQuiet and dxConfig["bShowLicenseAndDonationInfo"]:
       oConsole.fPrint();

```
....
 asApplicationOptionalArguments = url

In the previous release of BugId/cBugId this worked, now it seems broken.
Let me know if there is any additional information I can provide.

**Comment by SkyLined** [comment]
First, my apologies for the documentation in README.TXT being out of date; it is quite simple to run MSIE in BugId and have it open a specific URL:
```
python ./BugId.py msie --nApplicationMaxRunTime=10 -- http://www.google.com
```
I do not believe you need any of these patches. Please let me know if the above helps, or if you are trying to solve a specific issue that BugId currently cannot handle.

**Comment by SkyLined** [comment]
(In general the format is
```
python ./BugId.py <application keyword> <bugid arguments> -- <application arguments>
```
You can get a list of all known `application keywords` by running `python ./Bugid.py` (without arguments).
You can also run any application by providing the path to the executable instead of an application keyword.
```
python ./BugId.py path\to\executable.exe <bugid arguments> -- <application arguments>
```

**Comment by soiax** [comment]
This crash happens for me too... it happens with acrobatdc, foxit.. (all programs with space in path)...  isn't it something to do with space character in the path?

**Comment by SkyLined** [comment]
Yes, I found that problem too. Unfortunately, cdb.exe does not allow me to start a process using the `.create` command with a space in the path. I am currently working on a solution for that.

**Comment by SkyLined** [comment]
This should now be fixed.
