### ISSUE TITLE
Browser can't open

### ISSUE THREAD

**Issue by baptistapedro** [SkyLined/BugId#56]
Used BugId to check out a bug that make the browser crash, rebooted my machine and now when I try to run ./BugId.py "Edge path" the browser doesn't open because it fetch the last page opened (the bug one) so the browser never open just says "application is running...."

Runned with -v flag and can confirm that it prints out the info regarding the old bug yet
triggering a stack buffer overrun, how can i fix that ?
any way to make it forget about previous tests or?

**Comment by baptistapedro** [comment]
C:\Users\jitwei\Desktop\BugId>.\BugId.py "C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe" http://jitwei:28877
- You cannot provide multiple application binaries.
  (Did you perhaps forget to put -- before the start of the application arguments?)


C:\Users\jitwei\Desktop\BugId>.\BugId.py "C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe"
* Command line: C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe
* Process 10916/0x2AA4 (MicrosoftEdge.exe): Started C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe
* The application is running...

**Comment by SkyLined** [comment]
1) You do not start Edge by running MicrosoftEdge.exe: it is a UWP Application, so you should start it using "--uwp=<package name>!<app id>". In this case that would be `--uwp=Microsoft.MicrosoftEdge!MicrosoftEdge`. But it's easier to use the built in keyword "edge", as in `BugId.py edge`.
2) You must provide "--" before any application arguments, as in `BugId.py edge -- http://jitwei:28877`
3) Edge will remember the last open pages. To delete them use the `--bCleanup=true` argument, as in `BugId.py edge --bCleanup=true -- http://jitwei:28877`. Note that this cleanup is specific to edge and only works if you use the keyword `edge`: it has not effect if you use the `--uwp=...` argument.
