### ISSUE TITLE
--uwp conflict ?

### ISSUE THREAD

**Issue by baptistapedro** [SkyLined/BugId#58]
C:\Users\jitwei\Desktop\BugId>.\BugId.py -v --uwp=Microsoft.MicrosoftEdge!MicrosoftEdge
* UWP application id: MicrosoftEdge, package name: Microsoft.MicrosoftEdge
stdout>
stdout>Microsoft (R) Windows Debugger Version 10.0.14321.1024 AMD64
stdout>Copyright (c) Microsoft Corporation. All rights reserved.
stdout>
stdout>CommandLine: "C:\Windows\system32\cmd.exe" /K "ECHO OFF"
stdout>
stdout>************* Symbol Path validation summary **************
stdout>Response                         Time (ms)     Location
stdout>Deferred                                       cache*
stdout>Deferred                                       srv*http://msdl.microsoft.com/download/symbols
stdout>Symbol search path is: cache*;srv*http://msdl.microsoft.com/download/symbols
stdout>Executable search path is:
stdout>ModLoad: 00007ff6`55d60000 00007ff6`55db9000   cmd.exe
stdout>ModLoad: 00007ffe`e0a80000 00007ffe`e0c52000   ntdll.dll
stdout>ModLoad: 00007ffe`dfbb0000 00007ffe`dfc5c000   C:\Windows\System32\KERNEL32.DLL
stdout>ModLoad: 00007ffe`dda20000 00007ffe`ddc3d000   C:\Windows\System32\KERNELBASE.dll
stdout>ModLoad: 00007ffe`de010000 00007ffe`de0ae000   C:\Windows\System32\msvcrt.dll
stdout>(b4c.2a58): Break instruction exception - code 80000003 (first chance)
stdout>ntdll!LdrpDoDebuggerBreak+0x30:
stdout>00007ffe`e0b535f0 cc              int     3
stdout>0:000>
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .prompt_allow -dis -ea -reg -src -sym; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Display only the prompt
stdout><☺[☻{
stdout>Allow the following information to be displayed at the prompt:
stdout>(Other settings can affect whether the information is actually displayed)
stdout>  None
stdout>Do not allow the following information to be displayed at the prompt:
stdout>   sym - Symbol for current instruction
stdout>   dis - Disassembly of current instruction
stdout>    ea - Effective address for current instruction
stdout>   reg - Register state
stdout>   src - Source info for current instruction
stdout>}☻]☺>
stdout>0:000>
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .pcmd -s ".echo;"; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Output a CRLF after running the application
stdout><☺[☻{
stdout>Set prompt command
stdout>Per-prompt command is '.echo;'
stdout>}☻]☺>
stdout>0:000>
<stdin<
stdout>0:000>
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .lastevent; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get information about last event
stdout><☺[☻{
stdout>Last event: b4c.2a58: Break instruction exception - code 80000003 (first chance)
stdout>  debugger time: Tue Dec 12 03:27:27.799 2017 (UTC - 12:00)
stdout>}☻]☺>
stdout>0:000>
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ sxd *;sxi ld;sxi ud;sxd 0xC0000094;sxd 0xC0000095;sxd 0xC0000008;sxd 0xC0000235;sxd 0x80000004;sxd 0x4000001E;sxd 0xE06D7363;sxd 0x40080201;sxd 0x40080202;sxe cpr;sxe ibp;sxe epr;sxe aph;sxe 0xC0000005;sxe 0xC0000420;sxe 0x80000003;sxe 0xC000008C;sxe 0x80000002;sxe 0xC0000602;sxe 0x80000001;sxe 0xC000001D;sxe 0xC0000006;sxe 0xC0000096;sxe 0xC0000409;sxe 0xC00000FD;sxe 0x4000001F;sxe 0x80000007; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Setup exception handling
stdout><☺[☻{
stdout>}☻]☺>
stdout>0:000>
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .terminatepackageapp Microsoft.MicrosoftEdge_38.14393.1066.0_neutral__8wekyb3d8bbwe; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Terminate UWP application Microsoft.MicrosoftEdge
stdout><☺[☻{
stdout>}☻]☺>
stdout>0:000>
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .createpackageapp Microsoft.MicrosoftEdge_38.14393.1066.0_neutral__8wekyb3d8bbwe MicrosoftEdge ; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Start UWP application Microsoft.MicrosoftEdge
stdout><☺[☻{
stdout>Attach will occur on next execution
stdout>}☻]☺>
stdout>0:000>
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .time; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get debugger time
stdout><☺[☻{
stdout>Debug session time: Tue Dec 12 03:27:27.939 2017 (UTC - 12:00)
stdout>System Uptime: 3 days 22:28:47.707
stdout>Process Uptime: 0 days 0:00:00.134
stdout>  Kernel time: 0 days 0:00:00.000
stdout>  User time: 0 days 0:00:00.000
stdout>}☻]☺>
stdout>0:000>
<stdin<gn;
stdout>
stdout>************* Symbol Path validation summary **************
stdout>Response                         Time (ms)     Location
stdout>Deferred                                       cache*
stdout>Deferred                                       srv*http://msdl.microsoft.com/download/symbols
stdout>Symbol search path is: cache*;srv*http://msdl.microsoft.com/download/symbols
stdout>Executable search path is:
stdout>
stdout>1:002>
<stdin<
stdout>1:002>
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .lastevent; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get information about last event
stdout><☺[☻{
stdout>Last event: 162c.1a10: Create process 1:162c
stdout>  debugger time: Tue Dec 12 03:27:28.939 2017 (UTC - 12:00)
stdout>}☻]☺>
stdout>1:002>
* Process 5676/0x162C (MicrosoftEdge.exe): Started "C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe" -ServerName:MicrosoftEdge.AppXdnhjhccw3zf0j06tkg3jtqr00qdm0khc.mca
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .childdbg 1; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Debug child processes
stdout><☺[☻{
stdout>Processes created by the current process will be debugged
stdout>}☻]☺>
stdout>1:002>
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .time; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get debugger time
stdout><☺[☻{
stdout>Debug session time: Tue Dec 12 03:27:28.955 2017 (UTC - 12:00)
stdout>System Uptime: 3 days 22:28:48.723
stdout>Process Uptime: 0 days 0:00:00.927
stdout>  Kernel time: 0 days 0:00:00.000
stdout>  User time: 0 days 0:00:00.000
stdout>}☻]☺>
stdout>1:002>
<stdin<gh;
stdout>Page heap: pid 0x162C: page heap enabled with flags 0x2.
stdout>(162c.1a10): Break instruction exception - code 80000003 (first chance)
stdout>
stdout>1:002>
<stdin<
stdout>1:002>
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .lastevent; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get information about last event
stdout><☺[☻{
stdout>Last event: 162c.1a10: Break instruction exception - code 80000003 (first chance)
stdout>  debugger time: Tue Dec 12 03:27:28.986 2017 (UTC - 12:00)
stdout>}☻]☺>
stdout>1:002>
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .time; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get debugger time
stdout><☺[☻{
stdout>Debug session time: Tue Dec 12 03:27:29.002 2017 (UTC - 12:00)
stdout>System Uptime: 3 days 22:28:48.770
stdout>Process Uptime: 0 days 0:00:00.974
stdout>  Kernel time: 0 days 0:00:00.000
stdout>  User time: 0 days 0:00:00.000
stdout>}☻]☺>
stdout>1:002>
<stdin<gh;
stdout>(162c.2af0): Unknown exception - code 00000005 (first chance)
stdout>(162c.12b0): Windows Runtime Transform Error - code 40080202 (first chance)
stdout>(162c.12b0): Windows Runtime Transform Error - code 40080202 (first chance)
stdout> info: Suspending (Windows::ApplicationModel::Store::Preview::InstallControl::AppInstallManagerImpl::OnSuspend)
stdout>(162c.12b0): Windows Runtime Transform Error - code 40080202 (first chance)
stdout>(162c.12b0): Windows Runtime Transform Error - code 40080202 (first chance)
stdout>(162c.528): Unknown exception - code 800706ba (first chance)
stdout>(162c.528): Unknown exception - code 800706ba (first chance)
stdout>(162c.528): Unknown exception - code 800706ba (first chance)
stdout>(162c.528): Unknown exception - code 800706ba (first chance)
stdout>(162c.528): Unknown exception - code 800706ba (first chance)
stdout>
stdout>1:040>
<stdin<
stdout>1:040>
<stdin<.printf "%c%c%c%c%c\r\n", 0x3C, 0x1, 0x5B, 0x2, 0x7B; .block{ .lastevent; }; .printf "%c%c%c%c%c\r\n", 0x7D, 0x2, 0x5D, 0x1, 0x3E; $$ Get information about last event
stdout><☺[☻{
stdout>Last event: 162c.3204: Exit process 1:162c, code 1
stdout>  debugger time: Tue Dec 12 03:28:47.410 2017 (UTC - 12:00)
stdout>}☻]☺>
stdout>1:040>
* Process 5676/0x162C (MicrosoftEdge.exe): Terminated "C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe" -ServerName:MicrosoftEdge.AppXdnhjhccw3zf0j06tkg3jtqr00qdm0khc.mca
<stdin<q
stdout>quit:
+ The application terminated without a bug being detected.
  Application time: 79.439 seconds
  BugId overhead:   1.053 seconds

**Comment by baptistapedro** [comment]
By using --uwp= it opens the browser, I open the html file  that crash it in order to identify the bug class but no relevant output about the bug itself is stdout from BugId.
I cant use .\BugId.py edge because my Windows version is old and it requires a certain version to use "edge" as parameter. I think the above issue is because I'm unable to bCleanup it ?

**Comment by SkyLined** [comment]
If you are testing Edge on Windows versions before `15063`, you should be using https://github.com/SkyLined/EdgeDbg, specifically EdgeBugId.cmd: Microsoft changed the way UWP apps are loaded and BugId does not work on older versions. For that matter, EdgeBugId does not work on newer versions.
