### ISSUE TITLE
Bad 'import' latest version

### ISSUE THREAD

**Issue by baptistapedro** [SkyLined/BugId#62]
C:\Users\jitwei\Desktop\BugId>.\BugId.py edge
┌─ An internal exception has occured ──────────────────────────────────────────────────────────────────────────────────
│ NameError("global name 'oConsole' is not defined",)
│
│  Stack:
│   0 fasGetEdgeStaticArguments @ C:\Users\jitwei\Desktop\BugId\ddxApplicationSettings_by_sKeyword\ddxEdgeSettings_by_sKeyword.py/32
│      > oConsole.fPrint(ERROR, "Debugging Microsoft Edge directly using BugId is only supported on Windows");
│   1 fuMain @ C:\Users\jitwei\Desktop\BugId\BugId.py/711
│      > fasGetApplicationStaticArguments(bForHelp = False) or [];
│   2 C:\Users\jitwei\Desktop\BugId\BugId.py/877
│      > uExitCode = fuMain(sys.argv[1:]);
┖──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by SkyLined** [comment]
Thanks! A fix will bu uploaded soon!
