### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by jplopezy** [SkyLined/BugId#70]
This happens when I analyze an application per command line, if the argument does not crash in the application I analyze, nothing happens.

At the hour if I pass an argument that really generates a crash in the application that I analyze, it shows this.

┌─ An internal exception has occured ──────────────────────────────────────────────────────────────────────────────────
│ TypeError('__init__() takes exactly 6 arguments (5 given)',)
│
│  Stack:
│   0 foGetForProcessIdAndHandle @ C:\BugId-master\BugId\modules\mWindowsAPI\cProcessInformation.py/41
│      > return cProcessInformation(sProcessISA, None, None, None);
│   1 foGetForId @ C:\BugId-master\BugId\modules\mWindowsAPI\cProcessInformation.py/26
│      > return cProcessInformation.foGetForProcessIdAndHandle(uProcessId, hProcess);
│   2 oInformation @ C:\BugId-master\BugId\modules\mWindowsAPI\cConsoleProcess.py/138
│      > oSelf.__oInformation = cProcessInformation.foGetForId(oSelf.uId);
│   3 cCdbWrapper_fCdbStdInOutThread @ C:\BugId-master\BugId\modules\cBugId\cCdbWrapper_fCdbStdInOutThread.py/204
│      > sBinaryName = oConsoleProcess.oInformation.sBinaryName;
│   4 fCdbStdInOutThread @ C:\BugId-master\BugId\modules\cBugId\cCdbWrapper.py/447
│      > return cCdbWrapper_fCdbStdInOutThread(oCdbWrapper);
│   5 __fThreadWrapper @ C:\BugId-master\BugId\modules\cBugId\cCdbWrapper.py/271
│      > fActivity(*axActivityArguments);
┖──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by SkyLined** [comment]
This bug was in old code that has been rewritten. I'm sorry I never checked if this rewrite fixed the issue and closed the bug before. If you are still seeing this issue in the new code, please let me know and I will re-open the bug.
