### ISSUE TITLE
Debugging custom uwp packages

### ISSUE THREAD

**Issue by j00sean** [SkyLined/BugId#81]
First the help information how to debug uwp packages about is out-of-date. 
Fix: https://github.com/j00sean/BugId/commit/c034ba2f3cff801af07cd3d04149e53fc5c18023

Second i've made a simple uwp application using VS2017 and this is the BugId output:

C:\Users\IEUser\Desktop\BugId>python BugId.py -v --uwp="27ff0160-5084-4021-b249-bcfcf6ec046f!App"
┌─ Software license warning ───────────────────────────────────────────────────────────────────────────────────────────
│ You have no license for mFileSystem and your trial period will expire on 2018-06-30
│ You have no license for mWindowsAPI and your trial period will expire on 2018-06-30
│ You have no license for cBugId and your trial period will expire on 2018-06-30
│ You have no license for BugId and your trial period will expire on 2018-06-30
│ You have no license for mProductDetails and your trial period will expire on 2018-06-30
│ You have no license for oConsole and your trial period will expire on 2018-06-30
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
* UWP application id: App, package name: 27ff0160-5084-4021-b249-bcfcf6ec046f
┌─ An internal exception has occured ──────────────────────────────────────────────────────────────────────────────────
│ AssertionError("Unrecognized Get-AppxPackage output: '                    Microsoft.VCLibs.140.00.Debug_14.0.26428.1_x86__8wekyb3d8bbwe}'\r\n\r\n\r\nName              : 27ff0160-5084-4021-b249-bcfcf6ec046f\r\nPublisher         : CN=IEUser\r\nArchitecture      : X86\r\nResourceId        : \r\nVersion           : 1.0.0.0\r\nPackageFullName   : 27ff0160-5084-4021-b249-bcfcf6ec046f_1.0.0.0_x86__xnnwpqakf2yqj\r\nInstallLocation   : C:\\Users\\IEUser\\source\\repos\\App1\\App1\\bin\\x86\\Debug\\AppX\r\nIsFramework       : False\r\nPackageFamilyName : 27ff0160-5084-4021-b249-bcfcf6ec046f_xnnwpqakf2yqj\r\nPublisherId       : xnnwpqakf2yqj\r\nIsResourcePackage : False\r\nIsBundle          : False\r\nIsDevelopmentMode : True\r\nDependencies      : {Microsoft.NET.CoreRuntime.1.1_1.1.25915.0_x86__8wekyb3d8bbwe, \r\n                    Microsoft.VCLibs.140.00.Debug_14.0.26428.1_x86__8wekyb3d8bbwe}\r\nIsPartiallyStaged : False\r\nSignatureKind     : None\r\nStatus            : Ok\r\n\r\n\r\n",)
│
│  Stack:
│   0 __init__ @ C:\Users\IEUser\Desktop\BugId\modules\cBugId\cUWPApplication.py/38
│      > "Unrecognized Get-AppxPackage output: %s\r\n%s" % (repr(sLine), "\r\n".join(asQueryOutput));
....

There are lines not matching with "^(.*?)\s* : (.*)$". Therefore the assertion is triggered.
Fix: https://github.com/j00sean/cBugId/commit/689a8a70709f86a1fb0a5ea6d77c86fb3de418b3

**Comment by SkyLined** [comment]
Sorry for the delay on this.
* The documentation issue should have been fixed some time ago.
* I've updated the code that parses output to handle lists, see https://github.com/SkyLined/cBugId/commit/aa49a9d33634bb2a5bc84748596d88023c03f51d.

**Comment by j00sean** [comment]
Thanks a lot Berend!
