### ISSUE TITLE
An internal exception has occured

### ISSUE THREAD

**Issue by 1iK3** [SkyLined/BugId#86]
┌─ An internal exception has occured ──────────────────────────────────────────────────────────────────────────────────
│ WindowsError(2, '')
│
│  Stack:
│   0 _execute_child @ C:\Python27\lib\subprocess.py/644
│      > startupinfo)
│   1 __init__ @ C:\Python27\lib\subprocess.py/394
│      > errread, errwrite)
│   2 fasRunApplication @ C:\Fuzzing\BugId\modules\cBugId\cUWPApplication.py/10
│      > creationflags = subprocess.CREATE_NEW_PROCESS_GROUP,
│   3 __init__ @ C:\Fuzzing\BugId\modules\cBugId\cUWPApplication.py/26
│      > asQueryOutput = fasRunApplication("powershell", "Get-AppxPackage %s" % oUWPApplication.sPackageName);
│   4 __init__ @ C:\Fuzzing\BugId\modules\cBugId\cCdbWrapper.py/86
│      > oCdbWrapper.oUWPApplication = sUWPApplicationPackageName and cUWPApplication(sUWPApplicationPackageName, sUWPApplicationId) or None;
│   5 __init__ @ C:\Fuzzing\BugId\modules\cBugId\cBugId.py/112
│      > uMaximumNumberOfBugs = uMaximumNumberOfBugs,
│   6 fMain @ C:\Fuzzing\BugId\BugId.py/884
│      > uMaximumNumberOfBugs = guMaximumNumberOfBugs,
│   7 C:\Fuzzing\BugId\BugId.py/977
│      > fMain(sys.argv[1:]);
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by SkyLined** [comment]
Hi,

It looks like you do not have powershell installed on Windows. You can test this by opening a command-prompt and attempting to run `powershell`. Please let me know if doing that reports an error or not.

Also, could you please copy the version information from the error report?

**Comment by SkyLined** [comment]
No response, so I cannot fix this.
