### ISSUE TITLE
Can't find Windows SDK Path

### ISSUE THREAD

**Issue by baptistapedro** [SkyLined/BugId#87]
Hello,
Does BugID look for a specific path for Windows SDK?
I have the SDK on D:\ but still throw: ` BugId depends on Debugging Tools for Windows which was not found. `

Should I put the SDK on a specific path where BugID expects for?

Regards.

**Comment by baptistapedro** [comment]
Yeah that works out but I found out a new error.
I did set the path on dxConfig.py directly.

I'm running the cmd as follow: python BugId.py chrome_x64 -bGenerateReportHTML=true

`┌─ An internal exception has occured ──────────────────────────────────────────────────────────────────────────────────
│ AssertionError('End-of-command-output marker missing:\r\nNumeric expression missing from \'@!"chrome_child.dll!ovly_debug_event"; \'',)
│
│  Stack:
│   0 cCdbWrapper_fasExecuteCdbCommand @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\cCdbWrapper_fasExecuteCdbCommand.py/85
│      > "End-of-command-output marker missing:\r\n%s" % "\r\n".join(oEndOfCommandOutputMarkerMissingException.asCommandOutput);
│   1 fasExecuteCdbCommand @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\cCdbWrapper.py/368
│      > return cCdbWrapper_fasExecuteCdbCommand(oCdbWrapper, *axArguments, **dxArguments);
│   2 fasExecuteCdbCommand @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\cProcess.py/117
│      > return oProcess.oCdbWrapper.fasExecuteCdbCommand(sCommand, sComment, **dxArguments);
│   3 cProcess_fuGetAddressForSymbol @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\cProcess_fuGetAddressForSymbol.py/9
│      > srIgnoredErrors = gsrIgnoredErrors,
│   4 fuGetAddressForSymbol @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\cProcess.py/120
│      > return cProcess_fuGetAddressForSymbol(oProcess, sSymbol);
│   5 foCreate @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\cStack.py/241
│      > uFunctionAddress = oProcess.fuGetAddressForSymbol(oFunction.sName);
│   6 oStack @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\cBugReport.py/93
│      > oBugReport.__oStack = cStack.foCreate(oBugReport.__oProcess, oBugReport.__oWindowsAPIThread, oBugReport.uStackFramesCount);
│   7 fbApplyToBugReport @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\BugTranslations\cBugTranslation.py/98
│      > if oBugReport.oStack.fbTopFramesMatchSymbols(asAdditionalIrrelevantStackFrameSymbols, \
│   8 fApplyBugTranslationsToBugReport @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\BugTranslations\fApplyBugTranslationsToBugReport.py/53
│      > if oBugTranslation.fbApplyToBugReport(oBugReport):
│   9 foCreateForException @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\cBugReport.py/124
│      > fApplyBugTranslationsToBugReport(oBugReport);
│  10 cCdbWrapper_fCdbStdInOutHelperThread @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\cCdbWrapper_fCdbStdInOutHelperThread.py/409
│      > oException,
│  11 fCdbStdInOutHelperThread @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\cCdbWrapper.py/378
│      > return cCdbWrapper_fCdbStdInOutHelperThread(oCdbWrapper);
│  12 __fRun @ C:\Users\Gitinha\Desktop\BugId\modules\cBugId\cHelperThread.py/67
│      > oSelf.__fActivity(*oSelf.__axActivityArguments);
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────`

what is this about exaactly?

**Comment by SkyLined** [comment]
It appears that when BugId detected a crash and attempted to get the stack at the time of the crash, cdb.exe output something in a format that it does not expect. This is probably specific to the application you are testing, as I have not seen it before. I will try to work out if I can fix this, or else create a new version that reports more information about the problem to help me find out how to fix it.

Unfortunately, with the holidays comping up, it will probably be 2019 before I get around to addressing this issue. My apologies for this delay.

**Comment by baptistapedro** [comment]
Is this a common behavior for OOM or do you believe is bof related?

**Comment by SkyLined** [comment]
Sorry, been real busy lately. This is not specific to a particular type of bug. It may not even be a bug: BugId analyzes certain exceptions that can happen normally when an application is running. I'll try to find soime time to see what the root cause might be soon.

**Comment by SkyLined** [comment]
When I start Chrome, I get no crash with the latest version of BugId. If you can still reproduce, please let me know what html you are using to trigger this issue so I can investigate it.
