### ISSUE TITLE
 cBugID 2018-11-21: inconsistent variable usage for DMP file location

### ISSUE THREAD

**Issue by ngregoire** [SkyLined/BugId#89]
Using cBugID 2018-11-21 and trying to save DMP files to disk: the config file and documentation refer to dxConfig["sDumpPath"], but code uses dxConfig["sDumpFilePath"]. I had to modify "modules/cBugId/dxConfig.py"...

$ grep -r sDumpPath .
./dxConfig.py:                                                  # set using dxConfig["cBugId"]["sDumpPath"].
./modules/cBugId/dxConfig.py:  "sDumpPath": None,                    # Path where you want cBugId to save dump file. None = current folder.
./modules/cBugId/RELEASE NOTES.md:  `dxConfig["sDumpPath"]` (`None` -> current directory, which is the same as
./RELEASE NOTES.md:  `dxConfig["cBugId"]["sDumpPath"]` in `dxConfig.py` or by using the
./RELEASE NOTES.md:  `--cBugId.sDumpPath="path"` command-line argument. You can also request a

$ grep -r sDumpFilePath .
./modules/cBugId/cBugReport.py:      if dxConfig["sDumpFilePath"]:
./modules/cBugId/cBugReport.py:        sDumpFilePath = os.path.join(dxConfig["sDumpFilePath"], sDumpFileName);
./modules/cBugId/cBugReport.py:        sDumpFilePath = sDumpFileName;
./modules/cBugId/cBugReport.py:        sCommand = ".dump %s /%s \"%s\";" % (sOverwriteFlag, dxConfig["bFullDump"] and "f" or "ma", sDumpFilePath),

**Comment by SkyLined** [comment]
Fixed:
https://github.com/SkyLined/cBugId/commit/6977ea215e4fbea6436e5c00e4d3e79027289cbe

Released:
https://github.com/SkyLined/BugId/releases/tag/2019-03-04
